const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../static/index.html'),'utf8');
const start=source.indexOf('function _backgroundBackupStatus(');
const end=source.indexOf('let _engineStatusTimer=',start);
assert(start>0&&end>start);
const context=vm.createContext({Date});
vm.runInContext(source.slice(start,end),context);
const info=value=>{context.backup=value;return vm.runInContext('_backgroundBackupStatus(backup)',context);};
assert.equal(info({enabled:true,phase:'complete'}).attention,false);
assert.equal(info({enabled:true,phase:'downloading',overdue:true}).attention,false);
assert.match(info({enabled:true,phase:'downloading'}).note,/background/);
assert.equal(info({enabled:true,phase:'failed',error:'private backend detail'}).attention,true);
assert(!info({enabled:true,phase:'failed',error:'private backend detail'}).note.includes('private backend detail'));
assert.equal(info({enabled:true,phase:'icloud_upload_pending',overdue:false}).attention,false);
assert.equal(info({enabled:true,phase:'complete',overdue:true}).attention,true);
assert.equal(info({enabled:false,phase:'failed'}).note,'');
assert(!source.includes('document.body.prepend(note)'),'backup must not add a body-level layout banner');
console.log('Background backup UI: progress stays quiet, real failures remain discoverable, and private error text stays hidden.');
