#!/usr/bin/env python3
"""Guard Otomy dashboard parity rules before publishing.

This catches the exact regression where the frontend loads a correct dashboard
snapshot and then overwrites receivables/payables from stale archive balances.
It also checks that protected dashboard tabs are generated by the cloud sync
path, without localhost/Mac dashboard override files.
"""

from __future__ import annotations

import base64
import datetime as dt
import importlib.util
import json
import os
import sys
import argparse
from pathlib import Path
from zoneinfo import ZoneInfo


ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT_DIR = ROOT / "data" / "snapshot" / "api"

FORBIDDEN_SNAPSHOT_FETCH_ASSIGNMENTS = (
    "data.summary.",
    "data.top_receivables=",
    "data.top_payables=",
)

REQUIRED_DASHBOARD_SUMMARY_FIELDS = (
    "sales",
    "cash_collected",
    "credit_sales",
    "expenses",
    "expenses_before_director_adjustment",
    "profit",
    "margin_pct",
    "sales_qty_mt",
    "avg_rate_per_mt",
    "boulder_input_mt",
    "boulder_trips",
    "recovery_pct",
    "machine_hours",
    "machine_fuel_liters",
    "fuel_per_mt",
    "bank_balance",
    "cash_balance_office",
    "credit_payment_received",
    "selected_period_profit_per_tonne",
    "receivables",
    "payables",
)

VISIBLE_DASHBOARD_TILES = (
    ("Gross Sales", "sales"),
    ("Spot Sale (Bank+Cash)", "cash_collected"),
    ("Operating Expenses", "expenses"),
    ("Profit / MT", "selected_period_profit_per_tonne"),
    ("Period Profit", "profit"),
    ("Margin", "margin_pct"),
    ("Sales MT", "sales_qty_mt"),
    ("Avg Rate/MT", "avg_rate_per_mt"),
    ("Boulder Input", "boulder_input_mt"),
    ("Input Trips", "boulder_trips"),
    ("Expenses / MT", "expenses_per_mt"),
    ("Bank Balance", "bank_balance"),
    ("Cash Balance In Office", "cash_balance_office"),
    ("Credit Repayment", "credit_payment_received"),
    ("Credit Sales", "credit_sales"),
    ("Receivables", "receivables"),
    ("Payables", "payables"),
)

REQUIRED_CUSTOMER_RANGE_FIELDS = (
    "name",
    "material_sold",
    "range_credit_sales",
    "range_payment_received",
    "total_outstanding",
    "range_latest_sale_date",
    "latest_sale_date",
)


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def snapshot_key(url: str) -> str:
    encoded = base64.b64encode(url.encode("utf-8")).decode("ascii")
    return encoded.replace("+", "-").replace("/", "_").rstrip("=")


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text())
    except FileNotFoundError:
        fail(f"missing required file: {path.relative_to(ROOT)}")
    except json.JSONDecodeError as exc:
        fail(f"invalid JSON in {path.relative_to(ROOT)}: {exc}")


def required_preset_ranges() -> dict[str, tuple[dt.date, dt.date]]:
    configured_as_of = os.environ.get("OTOMY_VERIFY_AS_OF", "").strip()
    today = (
        dt.date.fromisoformat(configured_as_of)
        if configured_as_of
        else dt.datetime.now(ZoneInfo("Asia/Kolkata")).date()
    )
    week_start = today - dt.timedelta(days=today.weekday())
    last_month_end = today.replace(day=1) - dt.timedelta(days=1)
    last_month_start = last_month_end.replace(day=1)
    return {
        "today": (today, today),
        "yesterday": (today - dt.timedelta(days=1), today - dt.timedelta(days=1)),
        "thisweek": (week_start, today),
        "lastweek": (week_start - dt.timedelta(days=7), week_start - dt.timedelta(days=1)),
        "MTD": (today.replace(day=1), today),
        "lastmonth": (last_month_start, last_month_end),
    }


def dashboard_snapshot(start: dt.date | str, end: dt.date | str) -> tuple[str, dict]:
    start_s = str(start)
    end_s = str(end)
    url = f"/api/dashboard/control?from_date={start_s}&to_date={end_s}"
    snapshot_path = SNAPSHOT_DIR / f"{snapshot_key(url)}.json"
    return url, read_json(snapshot_path)


def api_snapshot(path: str) -> tuple[str, object]:
    snapshot_path = SNAPSHOT_DIR / f"{snapshot_key(path)}.json"
    return path, read_json(snapshot_path)


def number_value(value: object, label: str) -> float:
    try:
        return float(value or 0)
    except (TypeError, ValueError):
        fail(f"{label} must be numeric, got {value!r}")


def verify_negative_number_guard() -> None:
    gha_sync_path = ROOT / "scripts" / "gha_sync.py"
    spec = importlib.util.spec_from_file_location("otomy_gha_sync", gha_sync_path)
    if spec is None or spec.loader is None:
        fail("could not load gha_sync.py for number parser guard")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    samples = (
        ("-1,039,311.00", -1039311.0),
        ("₹-741,055.00", -741055.0),
        ("1,039,311.00", 1039311.0),
    )
    for raw, expected in samples:
        actual = round(float(module._num(raw)), 2)
        if actual != expected:
            fail(f"gha_sync.py _num({raw!r}) returned {actual}, expected {expected}")
    print("Negative number guard passed: ERP credit balances keep their sign.")


def verify_archive_balance_guard() -> None:
    source = (ROOT / "scripts" / "gha_sync.py").read_text()
    if 'if section == "balances":\n        return incoming\n' in source:
        fail("gha_sync.py must not blindly replace historical archive balance rows")
    if 'return incoming if _row_quality(section, incoming) >= _row_quality(section, existing) else existing' not in source:
        fail("gha_sync.py must preserve richer historical archive balance rows")
    if "repayments=seed_for(all_repayments, week_start, today)" not in source:
        fail("gha_sync.py weekly dashboard repayments must use all_repayments, not month-only repayments")
    print("Archive balance guard passed: historical rows and cross-month weekly repayments are protected.")


def payment_channel(mode: object) -> str:
    return "cash" if "CASH" in str(mode or "").upper() else "bank"


def sale_total(row: dict) -> float:
    return number_value(row.get("amount"), "sale.amount") + number_value(row.get("transport_charge"), "sale.transport_charge")


def sale_upi(row: dict) -> float:
    """UPI/bank portion of a sale — the captured ListSale Final UPI when present,
    else derived from payment_mode. Mirrors gha_sync _sale_channels so the bank page
    (which lists only the UPI portion of SPLIT sales) reconciles."""
    cash = number_value(row.get("cash_amount"), "sale.cash_amount")
    credit = number_value(row.get("credit_amount"), "sale.credit_amount")
    upi = number_value(row.get("upi_amount"), "sale.upi_amount")
    if cash + credit + upi > 0:
        return upi
    if str(row.get("payment_mode") or "").lower() == "credit" or payment_channel(row.get("payment_mode")) == "cash":
        return 0.0
    return sale_total(row)


def visible_tile_values(summary: dict) -> dict[str, float]:
    sales_qty_mt = number_value(summary.get("sales_qty_mt"), "summary.sales_qty_mt")
    expenses = number_value(summary.get("expenses"), "summary.expenses")
    values = {field: number_value(summary.get(field), f"summary.{field}") for field in REQUIRED_DASHBOARD_SUMMARY_FIELDS}
    values["expenses_per_mt"] = expenses / sales_qty_mt if sales_qty_mt else 0.0
    return values


def verify_credit_payment_uses_payment_total(snapshot: dict, label: str) -> None:
    summary = snapshot.get("summary") or {}
    actual = round(number_value(summary.get("credit_payment_received"), f"{label} summary.credit_payment_received"), 2)
    if "customer_repayments_payment_total" not in snapshot:
        fail(f"{label} missing customer_repayments_payment_total")
    payment_total = round(
        number_value(snapshot.get("customer_repayments_payment_total"), f"{label} customer_repayments_payment_total"),
        2,
    )
    if actual != payment_total:
        fail(
            f"{label} credit_payment_received must equal customer_repayments_payment_total "
            f"(actual={actual}, payment_total={payment_total})"
        )


def extract_snapshot_fetch(html: str, path: Path) -> str:
    start = html.find("async function snapshotFetch(url)")
    end = html.find("const _archiveCache", start)
    if start == -1 or end == -1 or end <= start:
        fail(f"could not locate snapshotFetch block in {path.relative_to(ROOT)}")
    return html[start:end]


def verify_frontend_guard() -> None:
    root_html = (ROOT / "index.html").read_text()
    static_html = (ROOT / "static" / "index.html").read_text()
    if root_html != static_html:
        fail("index.html and static/index.html differ; mirror Otomy frontend changes first")

    block = extract_snapshot_fetch(root_html, ROOT / "index.html")
    for needle in FORBIDDEN_SNAPSHOT_FETCH_ASSIGNMENTS:
        if needle in block:
            fail(
                "dashboard snapshotFetch must not overwrite visible tile values "
                f"after loading the snapshot; found {needle!r}"
            )
    for needle in (
        "async function _dailyOperatingBalance(toDate)",
        "balance_daily.json",
        "await renderControlRoom(controlData)",
        "_cashbook.bank=book.bank",
        "_cashbook.cash=book.cash",
        "const OtomyDataEngine={",
        "await OtomyDataEngine.range(",
        "OtomyDataEngine.summarize(",
        "OtomyDataEngine.day(",
        "const snapshotPreferredPath=new Set(",
        "String(requestedTo)>=today()",
        "String(requestedTo)===yesterday()",
        "'/api/sync/erp/cashbook'",
        "async function _buildCashBookFallback(",
        "const canonical=await api(`/api/sync/erp/cashbook?from_date=${from}&to_date=${to}`)",
        "const storedRows=months.flatMap(",
    ):
        if needle not in root_html:
            fail(f"frontend balance-chain guard missing {needle!r}")
    if "Verified balance adjustment (residual)" in root_html:
        fail("frontend must not render a generic residual balance adjustment")
    print("Frontend balance-chain guard passed: canonical cashbook/ledger paths are wired and residual rows are forbidden.")


def verify_daily_balance_chain() -> None:
    payload = read_json(ROOT / "data" / "balance_daily.json")
    previous = payload.get("previous_close") or {}
    opening = payload.get("today_opening") or {}
    today = payload.get("today_close") or {}
    if previous.get("as_of") != opening.get("as_of"):
        fail("balance_daily.json today_opening must use the previous close date")
    for field in ("bank_balance", "cash_balance_office"):
        previous_value = round(number_value(previous.get(field), f"previous_close.{field}"), 2)
        opening_value = round(number_value(opening.get(field), f"today_opening.{field}"), 2)
        if previous_value != opening_value:
            fail(
                f"balance_daily.json opening chain broken for {field}: "
                f"previous_close={previous_value} today_opening={opening_value}"
            )
        number_value(today.get(field), f"today_close.{field}")
    print("Daily balance chain passed: yesterday closing equals today's opening for cash and bank.")


def verify_no_balance_adjustment_rows() -> None:
    """Only localhost's two named verified anchor rows may appear in a book."""
    forbidden = []
    allowed = {
        "Verified balance adjustment (physical cash count)",
        "Verified balance adjustment (bank statement)",
    }

    def visit(value, path):
        if isinstance(value, dict):
            particulars = str(value.get("particulars") or "")
            if value.get("kind") == "adjustment" and particulars not in allowed:
                forbidden.append(path)
            for key, child in value.items():
                visit(child, f"{path}.{key}")
        elif isinstance(value, list):
            for index, child in enumerate(value):
                visit(child, f"{path}[{index}]")

    for path in (ROOT / "data").rglob("*.json"):
        try:
            visit(json.loads(path.read_text()), str(path.relative_to(ROOT)))
        except (OSError, json.JSONDecodeError):
            continue
    if forbidden:
        fail(f"published data contains forbidden balance-adjustment rows: {forbidden[:3]}")
    print("Balance-row guard passed: no residual or generic adjustment rows are published.")

def verify_sync_tolerance_guard() -> None:
    source = (ROOT / "scripts" / "gha_sync.py").read_text()
    required = (
        "ERP_FETCH_RETRIES",
        "ERP_DEBTOR_WORKERS",
        "_request_text_with_retry",
        "read_snapshot(",
        "fetch_result_or_saved(",
        "fetch_rows_or_saved(",
        "using archived non-empty rows",
        "using saved non-empty snapshot",
        "vendor payments fetch failed; using archived non-empty rows",
        "vendor payments fetch failed; no saved rows; continuing without vendor-payment rows",
        "window repayments ERP compute skipped",
        "replace_repayment_day(saved_mtd, today, repayments_today)",
        "optional debtor balance snapshot skipped",
        "repayments_movement = seed_for(all_repayments, movement_start, today)",
    )
    for needle in required:
        if needle not in source:
            fail(f"gha_sync.py lost cloud tolerance guard: missing {needle!r}")
    forbidden = (
        "lm_inter",
        "all_prefetch_dates = (boundary_dates | set(mtd_inter) | set(lm_inter))",
    )
    for needle in forbidden:
        if needle in source:
            fail(f"gha_sync.py must not fetch old debtor ranges on every recent sync: found {needle!r}")


def verify_cloud_independence_guard() -> None:
    source = (ROOT / "scripts" / "gha_sync.py").read_text()
    forbidden = (
        "local_dashboard_overrides",
        "LOCAL_DASHBOARD_OVERRIDES_PATH",
        "load_local_dashboard_overrides",
        "apply_local_dashboard_override",
    )
    for needle in forbidden:
        if needle in source:
            fail(f"gha_sync.py must be independent of localhost/Mac dashboard overrides: found {needle!r}")
    if (ROOT / "data" / "local_dashboard_overrides.json").exists():
        fail("data/local_dashboard_overrides.json must not exist; Otomy dashboard tabs must be cloud-generated")
    print("Cloud independence guard passed: no localhost/Mac dashboard overrides.")


def verify_payment_split_guard() -> None:
    """Ensure the per-ticket payment split (ListSale Final Cash/Credit/UPI) stays wired in,
    so SPLIT sales and bank-paid expenses can't silently collapse back to one channel."""
    source = (ROOT / "scripts" / "gha_sync.py").read_text()
    required = (
        "def fetch_sale_splits(",
        "def _sale_channels(",
        "def _cash_row_is_bank_expense(",
        "_sale_channels(sale)",
        "fetch_sale_splits(sess",
        "_cash_row_is_bank_expense(r, _bank_expenses)",
    )
    for needle in required:
        if needle not in source:
            fail(f"gha_sync.py lost payment-split handling: missing {needle!r}")
    print("Payment-split guard passed: ListSale Final Cash/Credit/UPI split is wired in.")


def verify_ledger_split_guard() -> None:
    """Ensure static archive Ledger View uses captured cash/credit/UPI splits.

    This protects against the old bug where a split UPI ticket was counted fully
    as bank in Ledger View while dashboard balances used the real split.
    """
    root_html = (ROOT / "index.html").read_text()
    required_helpers = (
        "function _saleChannels(r)",
        "function _saleCreditAmount(r){return _saleChannels(r).credit;}",
        "function _saleSpotAmount(r){const ch=_saleChannels(r);return ch.cash+ch.upi;}",
    )
    for needle in required_helpers:
        if needle not in root_html:
            fail(f"ledger split guard missing helper {needle!r}")

    def block_between(start_marker: str, end_marker: str) -> str:
        start = root_html.find(start_marker)
        end = root_html.find(end_marker, start)
        if start == -1 or end == -1 or end <= start:
            fail(f"ledger split guard could not locate block {start_marker!r}")
        return root_html[start:end]

    operating = block_between("async function _archiveOperatingBalances", "function _archiveCustomerSales")
    ledger = block_between("async function _archiveLedger", "async function archiveFetch")
    customer_sales = block_between("function _archiveCustomerSales", "function _archiveBalanceAsOf")

    for needle in ("const ch=_saleChannels(s);", "cash+=ch.cash;", "if(ch.upi&&inBank(s.date))bank+=ch.upi;"):
        if needle not in operating:
            fail(f"archive operating balance must use split sale channels: missing {needle!r}")
    for needle in (
        "spot=ds.reduce((s,r)=>s+_saleSpotAmount(r),0)",
        "credit=ds.reduce((s,r)=>s+_saleCreditAmount(r),0)",
        "credit_sale_amount:Math.round(credit*100)/100",
    ):
        if needle not in ledger:
            fail(f"archive ledger rows must use split sale channels: missing {needle!r}")
    for needle in ("g.credit_sale_amount+=ch.credit;", "g.cash_received+=ch.cash;", "g.bank_received+=ch.upi;"):
        if needle not in customer_sales:
            fail(f"archive customer sale totals must use split sale channels: missing {needle!r}")

    forbidden = (
        "if(_payChannel(s.payment_mode)==='cash')cash+=_saleTotal(s)",
        "bank+=_saleTotal(s)",
        "ds.filter(r=>String(r.payment_mode||'').toLowerCase()!=='credit')",
        "credit_sale_amount:Math.round((saleAmount-spot)*100)/100",
    )
    for block_name, block in (("operating", operating), ("ledger", ledger), ("customer_sales", customer_sales)):
        for needle in forbidden:
            if needle in block:
                fail(f"{block_name} archive logic must not use old payment_mode-only split: found {needle!r}")
    print("Ledger split guard passed: archive balances and ledger rows use cash/credit/UPI splits.")


def verify_no_vendor_payment_bank_guard() -> None:
    """Vendor payments are already represented in expenses, so Cash & Bank must not list them again."""
    root_html = (ROOT / "index.html").read_text()
    for needle in (
        "function _isVendorPaymentBankRow(row)",
        "function _withoutVendorPaymentRows(rows)",
        "if(u.pathname==='/api/sync/erp/bank')return _withoutVendorPaymentRows(data);",
        "return _withoutVendorPaymentRows(_rowsInRange(months,'bank',from,to))",
    ):
        if needle not in root_html:
            fail(f"frontend must filter vendor-payment bank rows: missing {needle!r}")

    source = (ROOT / "scripts" / "gha_sync.py").read_text()
    for needle in (
        "def _is_vendor_payment_bank_row(row):",
        "if _is_vendor_payment_bank_row(row):\n            continue",
        'if row.get("source") != "Sale" and not _is_vendor_payment_bank_row(row)',
        'if section == "bank" and _is_vendor_payment_bank_row(row):',
    ):
        if needle not in source:
            fail(f"gha_sync.py must drop vendor-payment bank rows: missing {needle!r}")

    append_start = source.find("vendor_payments, vendor_payments_fresh = fetch_vendor_payments_or_saved()")
    append_end = source.find("bank_rows = dedupe_bank_rows(bank_rows)", append_start)
    if append_start == -1 or append_end == -1 or append_end <= append_start:
        fail("could not locate vendor-payment/bank_rows block in gha_sync.py")
    append_block = source[append_start:append_end]
    if "bank_rows.append" in append_block or "UPI/Bank Vendor Payment" in append_block:
        fail("gha_sync.py must not append vendor payments to bank_rows")

    archive_start = source.find("def write_archive_updates(")
    archive_end = source.find("for as_of, snapshot in (balance_snapshots or {}).items():", archive_start)
    if archive_start == -1 or archive_end == -1 or archive_end <= archive_start:
        fail("could not locate archive update pre-balance block in gha_sync.py")
    archive_block = source[archive_start:archive_end]
    if "UPI/Bank Vendor Payment" in archive_block or "Vendor payment by bank/UPI" in archive_block:
        fail("gha_sync.py must not write vendor payments into archive bank rows")
    print("Vendor-payment bank guard passed: Cash & Bank no longer duplicates vendor expenses.")


def verify_customer_page_guard() -> None:
    root_html = (ROOT / "index.html").read_text()
    start = root_html.find("async function loadCustomers()")
    end = root_html.find("async function showCustLedger", start)
    if start == -1 or end == -1 or end <= start:
        fail("could not locate loadCustomers block")
    block = root_html[start:end]
    required = (
        "from_date=${from}&to_date=${to}&as_of=${to}",
        "Material Sold",
        "Credit Sale",
        "Payment Received",
        "Total Outstanding",
        "range_latest_sale_date||r.latest_sale_date",
    )
    for needle in required:
        if needle not in block:
            fail(f"customer page lost meaningful range column: missing {needle!r}")
    forbidden = ("GSTIN", "Phone", "ERP Received", "age_0_15", "age_16_30", "age_31_45", "age_45_plus")
    for needle in forbidden:
        if needle in block:
            fail(f"customer page table must not show old column {needle!r}")
    detail_start = root_html.find("function renderCustLedger()")
    detail_end = root_html.find("async function addReceipt", detail_start)
    if detail_start == -1 or detail_end == -1 or detail_end <= detail_start:
        fail("could not locate renderCustLedger block")
    detail = root_html[detail_start:detail_end]
    detail_required = (
        "rangeSales",
        "rangeReceipts",
        "cInRange",
        "Material Sold",
        "Opening",
        "Payment Received",
        "Closing (Outstanding)",
        "Ledger Account",
    )
    for needle in detail_required:
        if needle not in detail:
            fail(f"customer detail lost range-aware field: missing {needle!r}")
    detail_forbidden = ("ERP Received", "0-15 Days", "16-30 Days", "31-45 Days", "45+ Days")
    for needle in detail_forbidden:
        if needle in detail:
            fail(f"customer detail must not show old receivable card {needle!r}")
    print("Customer page guard passed: range-aware customer table and detail are wired in.")


def verify_pdf_export_guard() -> None:
    root_html = (ROOT / "index.html").read_text()
    required = (
        "downloadCurrentPagePdf()",
        "function downloadCurrentPagePdf()",
        "function runPrint(title, content, className='')",
        "function printViaIframe(",
        "function printViaBlob(",
        "window.print()",
        "function printDashboard(doPrint=true)",
        "Print / PDF",
        "CrusherOps — Dashboard Daily Report",
        "&nbsp;|&nbsp; Printed:",
        "OTOMY_APP_VERSION='2026-08-02-stale-guard-v1'",
    )
    for needle in required:
        if needle not in root_html:
            fail(f"PDF print guard missing {needle!r}")
    forbidden = (
        "return downloadPdfReport(pdfBuildPayload(",
        "downloadPdfReport(pdfBuildPayload('Dashboard Daily Report'",
    )
    for needle in forbidden:
        if needle in root_html:
            fail(f"PDF print guard found direct downloader path: {needle!r}")
    print("PDF print guard passed: all page PDF buttons use the browser print flow.")


def verify_customer_page_presets() -> None:
    checked = 0
    for preset, (start, end) in required_preset_ranges().items():
        url, rows = api_snapshot(f"/api/customers/?active_only=false&from_date={start}&to_date={end}&as_of={end}")
        if not isinstance(rows, list):
            fail(f"{preset} {url} must be a list")
        active_rows = [row for row in rows if isinstance(row, dict) and row.get("active", True)]
        for row in active_rows[:10]:
            for field in REQUIRED_CUSTOMER_RANGE_FIELDS:
                if field not in row:
                    fail(f"{preset} {url} customer row missing {field}")
            number_value(row.get("range_credit_sales"), f"{preset} customer range_credit_sales")
            number_value(row.get("range_payment_received"), f"{preset} customer range_payment_received")
            number_value(row.get("total_outstanding"), f"{preset} customer total_outstanding")
        checked += 1
    print(f"Customer page snapshot guard passed for {checked} tabs.")


def verify_all_dashboard_presets() -> None:
    checked = 0
    for preset, (start, end) in required_preset_ranges().items():
        url, snapshot = dashboard_snapshot(start, end)
        summary = snapshot.get("summary")
        if not isinstance(summary, dict):
            fail(f"{preset} {url} has no dashboard summary")
        for field in REQUIRED_DASHBOARD_SUMMARY_FIELDS:
            if field not in summary:
                fail(f"{preset} {url} missing summary.{field}")
            number_value(summary[field], f"{preset} {url} summary.{field}")
        verify_credit_payment_uses_payment_total(snapshot, f"{preset} {url}")
        tiles = visible_tile_values(summary)
        for tile_label, tile_key in VISIBLE_DASHBOARD_TILES:
            if tile_key not in tiles:
                fail(f"{preset} {url} missing visible tile {tile_label}")
        for list_field in ("top_receivables", "top_payables"):
            if list_field not in snapshot:
                fail(f"{preset} {url} missing {list_field}")
            if not isinstance(snapshot[list_field], list):
                fail(f"{preset} {url} {list_field} must be a list")
        checked += 1
    print(f"Dashboard preset guard passed for {checked} tabs.")


def verify_bank_page_presets() -> None:
    checked = 0
    for preset, (start, end) in required_preset_ranges().items():
        start_s, end_s = str(start), str(end)
        sales_url, sales = api_snapshot(f"/api/sales/?from_date={start_s}&to_date={end_s}")
        expenses_url, expenses = api_snapshot(f"/api/expenses/?from_date={start_s}&to_date={end_s}")
        control_url, control = dashboard_snapshot(start_s, end_s)
        bank_url, bank_rows = api_snapshot(f"/api/sync/erp/bank?from_date={start_s}&to_date={end_s}")
        if not isinstance(sales, list):
            fail(f"{preset} {sales_url} must be a list")
        if not isinstance(expenses, list):
            fail(f"{preset} {expenses_url} must be a list")
        if not isinstance(bank_rows, list):
            fail(f"{preset} {bank_url} must be a list")
        for row in bank_rows:
            if row.get("source") == "Vendor Payment" or row.get("bank_name") == "UPI/Bank Vendor Payment":
                fail(f"{preset} {bank_url} must not include duplicate vendor payment row {row.get('id')!r}")
        repayments = control.get("customer_repayments") or []
        if not isinstance(repayments, list):
            fail(f"{preset} {control_url} customer_repayments must be a list")

        # Bank page lists only the UPI/bank portion of each sale (SPLIT-aware).
        expected_sale_credit = round(sum(sale_upi(row) for row in sales), 2)
        expected_expense_debit = round(sum(
            number_value(row.get("amount"), "expense.amount")
            for row in expenses
            if payment_channel(row.get("payment_mode")) != "cash"
        ), 2)
        expected_repayment_credit = round(sum(
            number_value(row.get("bank_received"), "repayment.bank_received")
            or (
                number_value(row.get("payment_received", row.get("amount")), "repayment.payment_received")
                if payment_channel(row.get("mode")) != "cash"
                else 0.0
            )
            for row in repayments
        ), 2)

        actual_sale_credit = round(sum(
            number_value(row.get("credit"), "bank.credit")
            for row in bank_rows
            if row.get("bank_name") == "UPI/Bank Sale" or row.get("source") == "Sale"
        ), 2)
        actual_expense_debit = round(sum(
            number_value(row.get("debit"), "bank.debit")
            for row in bank_rows
            if row.get("bank_name") == "UPI/Bank Expense" or row.get("source") == "Expense"
        ), 2)
        actual_repayment_credit = round(sum(
            number_value(row.get("credit"), "bank.credit")
            for row in bank_rows
            if row.get("bank_name") == "UPI/Bank Credit Payment" or row.get("source") == "Credit Payment"
        ), 2)

        for label, expected, actual in (
            ("bank sale credits", expected_sale_credit, actual_sale_credit),
            ("bank expense debits", expected_expense_debit, actual_expense_debit),
            ("bank credit-payment credits", expected_repayment_credit, actual_repayment_credit),
        ):
            if actual + 0.01 < expected:
                fail(f"{preset} {bank_url} {label} missing rows: expected_at_least={expected} actual={actual}")
        checked += 1
    print(f"Bank page guard passed for {checked} tabs.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Verify Otomy dashboard and bank-page parity guards.")
    parser.add_argument(
        "--code-only",
        action="store_true",
        help="Only check frontend/code invariants; sync workflows run full data checks after generation.",
    )
    args = parser.parse_args()
    verify_frontend_guard()
    verify_sync_tolerance_guard()
    verify_negative_number_guard()
    verify_archive_balance_guard()
    verify_payment_split_guard()
    verify_ledger_split_guard()
    verify_no_vendor_payment_bank_guard()
    verify_customer_page_guard()
    verify_pdf_export_guard()
    if args.code_only:
        print("Code-only parity guard passed.")
        return
    verify_daily_balance_chain()
    verify_no_balance_adjustment_rows()
    verify_all_dashboard_presets()
    verify_bank_page_presets()
    verify_customer_page_presets()
    verify_cloud_independence_guard()


if __name__ == "__main__":
    main()
